version: '3.8'

services:
  api:
    image: 503079484440.dkr.ecr.us-east-1.amazonaws.com/triggy-backend:latest
    ports:
      - "80:3000"
    env_file:
      - .env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 0
      resources:
        limits:
          cpus: '1.5'
          memory: '1536M'
        reservations:
          cpus: '1'
          memory: '1024M'