version: '3.8'

services:
  api:
    image: 978820379464.dkr.ecr.us-east-1.amazonaws.com/triggy-backend:latest
    ports:
      - "80:3000"
    env_file:
      - .env
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 0
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M