service: triggy

frameworkVersion: '4'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0
    stage: ${self:provider.stage}
    prefix: v1
    printOutput: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
    STAGE: ${self:provider.stage}
    QUEUE_URL: !Ref WebhookQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: !GetAtt WebhookQueue.Arn
  
  httpApi:
    cors: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"
    target: 'node20'
    platform: 'node'

package:
  individually: true
  exclude:
    - node_modules/**
    - test/**
    - .git/**
    - .gitignore
    - README.md
    - .eslintrc.js
    - .prettierrc
    - docker-compose.yaml
    - nest-cli.json
  
functions:
  webhooks:
    handler: src/serverless/handlers/webhooks.handler
    events:
      - httpApi:
          path: /webhooks/{id}
          method: post

resources:
  Resources:
    WebhookQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-webhooks-queue