export const ErrorCodes = {
  INVALID_TOKEN: 'INVALID_TOKEN',

  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  INVALID_COUPON: 'INVALID_COUPON',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  INVALID_PLAN: 'INVALID_PLAN',

  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_STATS_NOT_FOUND: 'USER_STATS_NOT_FOUND',
  SIGNATURE_NOT_FOUND: 'SIGNATURE_NOT_FOUND',

  INTEGRATION_NOT_FOUND: 'INTEGRATION_NOT_FOUND',
  INTEGRATION_QUOTA_EXCEEDED: 'INTEGRATION_QUOTA_EXCEEDED',

  WEBHOOK_NOT_FOUND: 'WEBHOOK_NOT_FOUND',
  WEBHOOK_QUOTA_EXCEEDED: 'WEBHOOK_QUOTA_EXCEEDED',

  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
