export const ErrorCodes = {
  INVALID_TOKEN: 'INVALID_TOKEN',

  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  INVALID_COUPON: 'INVALID_COUPON',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',

  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_STATS_NOT_FOUND: 'USER_STATS_NOT_FOUND',
  SIGNATURE_NOT_FOUND: 'SIGNATURE_NOT_FOUND',

  INTEGRATION_NOT_FOUND: 'INTEGRATION_NOT_FOUND',
  INTEGRATION_QUOTA_EXCEEDED: 'INTEGRATION_QUOTA_EXCEEDED',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
